module.exports = {
    // Emit
    NEW_CHANNEL: "NEW_CHANNEL",
    DELETE_CHANNEL: "DELETE_CHANNEL",
    USER_HAS_JOINED_CHANNEL: "USER_HAS_JOINED_CHANNEL",
    USER_HAS_LEFT_CHANNEL: "USER_HAS_LEFT_CHANNEL",
    NEW_MESSAGE: "NEW_MESSAGE",
    EDIT_MESSAGE: "EDIT_MESSAGE",
    DELETE_MESSAGE: "DELETE_MESSAGE",

    // Receive
    NEW_USER_CHANNEL: "NEW_USER_CHANNEL",
    USER_LEFT_CHANNEL: "USER_LEFT_CHANNEL",
    ADD_CHANNELS: "ADD_CHANNELS"
};