module.exports = {
    // Emit
    NEW_CHANNEL: "NEW_CHANNEL",
    DELETE_CHANNEL: "DELETE_CHANNEL",
    USER_HAS_JOINED_CHANNEL: "USER_HAS_JOINED_CHANNEL",
    USER_HAS_LEFT_CHANNEL: "USER_HAS_LEFT_CHANNEL",

    // Receive
    NEW_USER_CHANNEL: "NEW_USER_CHANNEL",
    USER_LEFT_CHANNEL: "USER_LEFT_CHANNEL",
};