export enum LoginActionTypes {
    LOGIN_REQUEST = "AUTH_REQUEST",
    LOGIN_SUCCESS = "AUTH_SUCCESS",
    LOGIN_FAILURE = "AUTH_FAILURE",
}

export enum RegisterActionTypes {
    REGISTER_REQUEST = "REGISTER_REQUEST",
    REGISTER_SUCCESS = "REGISTER_SUCCESS",
    REGISTER_FAILURE = "REGISTER_FAILURE"
}