module.exports = {
    GET_CHANNELS: "GET_CHANNELS",
    SET_CHANNELS: "SET_CHANNELS",
    SET_CHANNELS_REQUEST: "GET_CHANNELS_REQUEST",
    CREATE_CHANNEL: "CREATE_CHANNEL",
    CREATE_CHANNEL_REQUEST: "CREATE_CHANNEL_REQUEST",
};