module.exports = {
    GET_CHANNELS: "GET_CHANNELS",
    GET_CHANNELS_REQUEST: "GET_CHANNELS_REQUEST",

    CHANNEL_REQUEST: "ADD_NEW_CHANNEL",
    ADD_NEW_CHANNEL: "ADD_NEW_CHANNEL",
    DELETE_CHANNEL: "DELETE_CHANNEL",

    SET_DISPLAYED_CHANNEL: "SET_DISPLAYED_CHANNEL",

    ADD_ERROR: "ADD_ERROR",
    REMOVE_ERROR: "REMOVE_ERROR",

    SET_CURRENT_USER: "SET_CURRENT_USER",

    AUTH_REQUEST: "AUTH_REQUEST",

    GET_MESSAGES: "GET_MESSAGES",
    MESSAGES_REQUEST: "MESSAGES_REQUEST",

    TOGGLE_MENU: "TOGGLE_MENU",
    TOGGLE_ADD_CHANNEL: "TOGGLE_ADD_CHANNEL",
    TOGGLE_PAGE_ACTION: "TOGGLE_ADD_CHANNEL"
};