module.exports = {
    GET_CHANNELS: "GET_CHANNELS",
    GET_CHANNELS_REQUEST: "GET_CHANNELS_REQUEST",
    ADD_ERROR: "ADD_ERROR",
    REMOVE_ERROR: "REMOVE_ERROR",
    SET_CURRENT_USER: "SET_CURRENT_USER",
    AUTH_REQUEST: "AUTH_REQUEST",
    ADD_NEW_CHANNEL: "ADD_NEW_CHANNEL",
    CHANNEL_REQUEST: "ADD_NEW_CHANNEL",
    DELETE_CHANNEL: "DELETE_CHANNEL",
};